export const RESOURCE_NOT_LOADING = "RESOURCE_NOT_LOADING";
export const COURSE_NOT_FOUND = "COURSE_NOT_FOUND";
export const CHECKPOINT_NOT_FOUND = "CHECKPOINT_NOT_FOUND";
export const TOTAL_PANIC = "TOTAL_PANIC";
export const NO_SEARCH_RESULTS = "NO_SEARCH_RESULTS";
