export { default as AboutView } from "./AboutView";
export { default as ContributeView } from "./ContributeView";
export { default as CollectionView } from "./CollectionView";
export { default as CourseView } from "./CourseView";
export { default as FAQView } from "./FAQView";
export { default as IntroductionView } from "./IntroductionView";
export { default as NoSearchResultsView } from "./NoSearchResultsView";
export { default as TotalPanicView } from "./TotalPanicView";
export { default as CourseNotFoundView } from "./CourseNotFoundView";
